export enum JobPositionEnum {
  GRILL_COOK = "GRILL_COOK",
  COOK = "COOK",
  KITCHEN_ASSISTANT = "KITCHEN_ASSISTANT",
  CASHIER = "CASHIER",
  WAITER = "WAITER",
  DELIVERY_DRIVER = "DELIVERY_DRIVER",
  ADMINISTRATOR = "ADMINISTRATOR",
  OTHER = "OTHER",
}
